### ISSUE TITLE
"Cross-site POST form submissions are forbidden"

### ISSUE THREAD

**Issue by LeqitDev** [gornostay25/svelte-adapter-bun#54]
Just encountered this error while testing my website in production.

Setup:
I'm using docker with nginx proxy manager as a reverse proxy.

So i was building my multi-container through this docker-compose.yml
```
version: '3.9'
services:
  db:
    restart: 'always'
    build: './pocketbase'
    expose:
      - 80
    ports:
      - ${PORTDB:-8081}:80
    environment:
      FRONTEND_URL: http://web:3001
    volumes:
      - dbdata:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      - nginx-network
  web:
    restart: 'always'
    build: 
      context: './web'
      dockerfile: 'Dockerfile'
      args:
        PUBLIC_DATABASE: ${PUBLIC_DATABASE:-https://api.domain.tld/sub}
    ports:
      - ${PORTWEB:-8080}:3001
    expose:
      - 3001
    environment:
      PORT: 3001
      PUBLIC_DATABASE: ${PUBLIC_DATABASE:-https://api.domain.tld/sub}
      ORIGIN: https://sub.domain.tld
    networks:
      - nginx-network

volumes:
  dbdata:

networks:
  nginx-network:
    name: nginx-proxy-manager_default
    external: true
```

With my web Dockerfile looking like this:
```
FROM oven/bun as builder

ARG PUBLIC_DATABASE
ENV PUBLIC_DATABASE=${PUBLIC_DATABASE}

WORKDIR /app

COPY . .
ENV ORIGIN=https://sub.domain.tld

RUN bun i
RUN bun run build

FROM oven/bun
COPY --from=builder /app/build .

ENV ORIGIN=https://sub.domain.tld

EXPOSE 3001

CMD [ "bun", "index.js" ]
```
I know that the ORIGIN env is set multiple times just wanted to check that it wasn't on the wrong spot.

I was also printing the url.origin in the load function in +layout.server.ts which resulted in the following output:
`http://sub.domain.tld`

Running `bun --print process.env` also tried with (Bun.env) resulted in:
```
{
  ...,
  ORIGIN: "https://sub.domain.tld",
  ...,
}
```

What i discovered was that when i didnt enforce https with my reverse proxy and use the website with "http://" it just works fine but that isnt the way i think

Hope somebody can help fixing this monster that cost me more then 2 hours of trying and failing
If you need some more infos just ask for it
